import groovy.util.logging.Slf4j;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'gabriel.oliveira' at '28/06/16 16:56' with Gradle 2.13
 *
 * @author gabriel.oliveira, @date 28/06/16 16:56
 */
@Slf4j
public class AppTest {
	
}
