package br.com.mvsistemas.gcm.portal.executor.chef.main;
/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'gabriel.oliveira' at '28/06/16 16:56' with Gradle 2.13
 *
 * @author gabriel.oliveira, @date 28/06/16 16:56
 */

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.EnableAutoConfiguration;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.ComponentScan;

@SpringBootApplication
@EnableAutoConfiguration
@ComponentScan("br.com.mvsistemas.gcm.portal.executor.chef")
public class App {
	
	public App() {
		
	}
	
	public static void main(String[] args) {
		SpringApplication.run(App.class, args);
	}
}
